# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 09:15
from __future__ import unicode_literals

import Gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Gallery.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('image_title', models.CharField(blank=True, max_length=250)),
                ('image_description', models.TextField(blank=True)),
                ('image_id', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
