# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionalPostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_distict', models.CharField(max_length=100)),
                ('divisional_category_slug', models.CharField(db_index=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Divisional Post Category',
                'verbose_name_plural': 'Divisional Post Category',
                'ordering': ['name_of_distict'],
            },
        ),
        migrations.CreateModel(
            name='DivisionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('category_slug', models.CharField(db_index=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'General Category',
                'verbose_name_plural': 'General Category',
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(db_index=True, max_length=250, unique=True)),
                ('content', models.TextField()),
                ('featured_image_id', models.CharField(max_length=250)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('publish', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('private', 'Private')], default='publish', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_featured', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=100)),
                ('total_page_views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.PostCategory')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.DivisionName')),
                ('divisional_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.DivisionalPostCategory')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.AddField(
            model_name='divisionalpostcategory',
            name='name_of_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Post.DivisionName'),
        ),
    ]
