# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20180421_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='is_image_gallery',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=200),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='is_video_gallery',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=200),
        ),
    ]
