# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstantArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page_ID', models.CharField(blank=True, default='', max_length=200, verbose_name='Facebook Page ID')),
                ('article_style', models.CharField(blank=True, default='', max_length=200, verbose_name='Article Style')),
                ('copyright', models.CharField(blank=True, default='', max_length=200, verbose_name='Copyright')),
                ('domain_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Domain Name')),
                ('ads_code', models.CharField(blank=True, default='', max_length=200, verbose_name='Ads Code')),
                ('google_analytics', models.TextField(blank=True, default='', verbose_name='Google Analytics Code')),
            ],
        ),
    ]
