# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 09:15
from __future__ import unicode_literals

import Homepage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterAboveSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_above_1', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footer_above_1', to='Post.PostCategory')),
                ('footer_above_2', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footer_above_2', to='Post.PostCategory')),
                ('footer_above_3', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footer_above_3', to='Post.PostCategory')),
                ('footer_above_4', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='footer_above_4', to='Post.PostCategory')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_site', models.CharField(blank=True, max_length=200)),
                ('site_tag_line', models.CharField(blank=True, max_length=200)),
                ('site_logo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=Homepage.models.upload_location_site_logo, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('site_favicon', models.ImageField(blank=True, height_field='width_field_fav', null=True, upload_to=Homepage.models.upload_location_site_fav, width_field='height_field_fav')),
                ('height_field_fav', models.IntegerField(default=32)),
                ('width_field_fav', models.IntegerField(default=32)),
            ],
        ),
        migrations.CreateModel(
            name='HomepageMiddleSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_code_1', models.TextField(blank=True, default='')),
                ('ads_code_2', models.TextField(blank=True, default='')),
                ('fb_page_code', models.TextField(blank=True, default='', help_text="You will get page plugin from <a href='https://developers.facebook.com/docs/plugins/page-plugin/' target='_blank'>here.</a>")),
                ('part_one_left', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Left', to='Post.PostCategory')),
                ('part_two_right', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Middle', to='Post.PostCategory')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageMiddleSectionBelow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_one', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Post.PostCategory')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageMiddleSectionBelowTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_one_two', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Post.PostCategory')),
            ],
        ),
        migrations.CreateModel(
            name='InsertHeaderFooter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_code', models.TextField(blank=True, default='')),
                ('footer_code', models.TextField(blank=True, default='')),
            ],
        ),
    ]
