# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_ads_970x90', models.TextField(blank=True, default='')),
                ('sidebar_1', models.TextField(blank=True, default='')),
                ('sidebar_2', models.TextField(blank=True, default='')),
                ('sidebar_3', models.TextField(blank=True, default='')),
            ],
        ),
    ]
