# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_homepageads'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetailPageAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_sidebar_160x900', models.TextField(blank=True, default='')),
                ('right_sidebar_1', models.TextField(blank=True, default='')),
                ('right_sidebar_2', models.TextField(blank=True, default='')),
                ('right_sidebar_3', models.TextField(blank=True, default='')),
                ('before_post', models.TextField(blank=True, default='')),
                ('after_post', models.TextField(blank=True, default='')),
            ],
        ),
    ]
