# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_postdetailpageads'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRightSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_right_text', models.TextField(blank=True, default='')),
                ('about_summery', models.TextField(blank=True, default='')),
                ('about_full', models.TextField(blank=True, default='')),
                ('editor_email', models.CharField(blank=True, default='', max_length=250)),
                ('privary_policy', models.TextField(blank=True, default='')),
                ('conatct', models.TextField(blank=True, default='')),
                ('advertisement', models.TextField(blank=True, default='')),
            ],
        ),
    ]
