# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_auto_20180428_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_app_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Facebook App ID')),
                ('facebook_page_id', models.CharField(blank=True, default='', max_length=200, verbose_name='Facebook Page ID')),
                ('meta_description', models.TextField(blank=True, default=True, verbose_name='Meta Description')),
                ('domain_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Domain Name')),
                ('site_title', models.CharField(blank=True, default='', max_length=200, verbose_name='Site Title')),
            ],
        ),
    ]
