# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='meta_description',
            field=models.TextField(blank=True, default='', verbose_name='Meta Description'),
        ),
    ]
